export const SIGNUP : string = "SIGNUP"
export const LOGIN : string = "LOGIN"
export const UNVALIDATED : string = "UNVALIDATED"
export const AUTHORIZING : string = "AUTHORIZING"
export const CHANGETRUE : string = "CHANGETRUE"